// src/app/layout.tsx
import type { Metadata, Viewport } from "next";
import { Providers } from "@/components/Provider/Providers";
import "./globals.css";
// [ลบ] บรรทัดนี้ออก: import Script from "next/script";

// ✨ [เพิ่ม] Import Component ใหม่ที่เราสร้าง
import LongdoScriptLoader from "@/components/Script/LongdoScriptLoader";

export const metadata: Metadata = {
  title: "OK Mobile ประเมินสภาพเครื่อง",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
      <LongdoScriptLoader />
    </html>
  );
}
