import type { Metadata, Viewport } from "next";
import { Providers } from "@/components/Provider/Providers";
import "./globals.css";
import Script from "next/script";

export const metadata: Metadata = {
  title: "OK Mobile ประเมินสภาพเครื่อง",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
      <Script src="https://api.longdo.com/map/?key=YOUR_API_KEY" />
      <Script src="https://api.longdo.com/address-form/js/addressform.js" />
    </html>
  );
}
